name: CD to Minikube

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          for module in api-gateway persons-service image-requests-service web-ui; do
            docker build -t ghcr.io/${{ github.repository }}/$module:${{ github.sha }} ./$module
            docker push ghcr.io/${{ github.repository }}/$module:${{ github.sha }}
          done

      - name: Set up Minikube
        run: |
          chmod +x ci-cd/scripts/setup-minikube.sh
          ci-cd/scripts/setup-minikube.sh

      - name: Deploy to Minikube
        run: |
          chmod +x ci-cd/scripts/deploy-kubernetes.sh
          ci-cd/scripts/deploy-kubernetes.sh ${{ github.sha }}
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/api-gateway
          kubectl rollout status deployment/persons-service
          kubectl rollout status deployment/image-requests-service
          kubectl rollout status deployment/web-ui
          minikube service web-ui --url