global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'persons-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['persons-service:8080']
  - job_name: 'image-requests-service'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['image-requests-service:8000']
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['api-gateway:8080']