services:
  image-requests-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/image_requests_db
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
    depends_on:
      - mongodb
    volumes:
      - image-requests-logs:/logs
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  mongo-data:
  image-requests-logs:

networks:
  app-network:
    driver: bridge