apiVersion: apps/v1
kind: Deployment
metadata:
  name: persons-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persons-service
  template:
    metadata:
      labels:
        app: persons-service
    spec:
      containers:
        - name: persons-service
          image: persons-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: persons-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: persons-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: persons-secrets
                  key: jwt-secret