apiVersion: v1
kind: Service
metadata:
  name: persons-service
  namespace: default
spec:
  selector:
    app: persons-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP