apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-requests-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-requests-service
  template:
    metadata:
      labels:
        app: image-requests-service
    spec:
      containers:
        - name: image-requests-service
          image: image-requests-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mongodb-uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: image-secrets
                  key: jwt-secret