apiVersion: v1
kind: Service
metadata:
  name: image-requests-service
  namespace: default
spec:
  selector:
    app: image-requests-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP