name: API Gateway CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'api-gateway/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file api-gateway/pom.xml
      - name: Build Docker image
        run: docker build -t api-gateway:latest api-gateway/
      - name: Deploy to Minikube
        run: |
          minikube start
          kubectl apply -f api-gateway/kubernetes/deployment.yaml