apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  redis-host: "redis"
  redis-port: "6379"
  mongodb-uri: "mongodb://mongodb:27017/image_requests_db"
  postgres-url: "jdbc:postgresql://postgresql:5432/personsdb"
  api-url: "http://api-gateway:8080/api"