apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  jwt-secret: eW91ci1zZWN1cmUtanctc2VjcmV0LWtleQ== # your-secure-jwt-secret-key
  postgres-user: YWRtaW4= # admin
  postgres-password: c2VjdXJlcGFzc3dvcmQ= # securepassword